### ISSUE TITLE
Issue with Australian dollar (aud) currency

### ISSUE THREAD

**Issue by SoftBytes** [stripe/stripe-payments-demo#154]
# Bug report
Changing currency in config to Australian dollar causes issue payment.
## Describe the bug

I was trying to change currency in config.js to 'aud', but got an issue with payment processing. 
Button  shows 'Processing' and I got an error in console:
Uncaught (in promise) TypeError: paymentIntent is undefined
    <anonymous> http://localhost:8000/javascripts/payments.js:289
    EventListener.handleEvent* http://localhost:8000/javascripts/payments.js:259
    async* http://localhost:8000/javascripts/payments.js:930
payments.js:289:1

## To Reproduce
1. Update config.js currency to 'aud'
2. Restart server and navigate to app.
3. Enter Shipping/Billing details and card number.
4. Hit Pay

## Expected behavior
Payment succeeds and Success page displayed

##Actual Result
Payment is not processed, button shows Processing... and console shows error

## System information

- OS: Windows
- Browser Firefox
- Server environment Node.js

## Additional context

Would be great if you can assist with this issue in timely manner. 
Thank you in advance.

**Comment by willock-stripe** [comment]
Hi @SoftBytes –

Thanks for the report. The Javascript error you're reporting [0] is ultimately raised because the call to `/payment-intent` is returning a HTTP 500 with an error [1].

I think it would be worthwhile adding some guardrails to prevent this error, but as a workaround, you can simply disable the currency-specific payment methods in `config.js`. Card, Ali Pay, and WeChat Pay should work fine with AUD.

[0] `TypeError: paymentIntent is undefined`
[1] `The currency provided (aud) is invalid for one or more payment method types on this PaymentIntent. The payment method type bancontact only supports the following currencies: eur. Either correct the provided currency, or use a different PaymentIntent to accept this payment method type.`

**Comment by SoftBytes** [comment]
Thank @willock-stripe , we got it figured out eventually.
