### ISSUE TITLE
Google brand guidelines

### ISSUE THREAD

**Issue by AlanFoster** [stripe/stripe-payments-demo#46]
Hey, I noticed that the request button for Google currently looks like:

![image](https://user-images.githubusercontent.com/1271782/52647350-7610b500-2edc-11e9-8ee6-a26deb7429a2.png)

But according to [Google's brand guidelines](https://developers.google.com/pay/api/web/guides/brand-guidelines), it should be visually represented as:

![image](https://user-images.githubusercontent.com/1271782/52647319-698c5c80-2edc-11e9-8c92-e0945e0c029b.png)

![image](https://user-images.githubusercontent.com/1271782/52647481-b4a66f80-2edc-11e9-89e2-232152332e38.png)

Is there any requirement to update this demo to align with Google's Style requirements? 🤔

**Comment by thorsten-stripe** [comment]
@AlanFoster thanks. Today Stripe.js relies on the payment request API to make Google Pay available. Since the PRAPI also provides other payment instruments (e.g. stored card on Chrome) this button is not Google Pay branded.

If you want access to the cross-browser Google Pay button you can implement Google's pay.js which doesn't rely on the payment request API: https://developers.google.com/pay/api/web/setup

You can see an implementation of this on the following feature branch: https://github.com/stripe/stripe-payments-demo/tree/payment-intent-experiment

You can see the logic here to evaluate when to show the Google Pay branded button vs. the payment request button: https://github.com/stripe/stripe-payments-demo/blob/payment-intent-experiment/public/javascripts/payments.js#L212-L248

I hope this helps clear things up, but do reopen if you have more questions!
