### ISSUE TITLE
How to pass custom data via html element?

### ISSUE THREAD

**Issue by Syirrus** [stripe/stripe-payments-demo#49]
I'm a bit of a newbie, when it comes to this stuff, but I have gotten your script to work.  It works beautifully and thank you for putting on GitHub. 

I cannot figure out how to pass custom field data through so that I can query it using Stripes API.  I need to pass a userId via a hidden html element. What JSON object key should this be place under? It looks like I would need to update the payments.js so that I could grab the hidden html element, but from there I'm lost.

**Comment by karlr-stripe** [comment]
Hey @Syirrus, it sounds like what you are looking for here is [metadata](https://stripe.com/docs/api/metadata), which is arbitrary information you can attach to an object in Stripe's API. 

In terms of implementing that as part of this demo, you'd want to add your hidden input tag in index.html:
```
<input type="hidden" id="user_id" value="user_123">
```

and then access it when the form is submitted:
```
var userId = document.getElementById("user_id").value
```

You might then pass it to the `payOrder` function, in order to send the value to the backend, around here :
https://github.com/stripe/stripe-payments-demo/blob/c242611d0abd2ca99ec0557d3cf5855657ade2cc/public/javascripts/payments.js#L391 
```
order.userId = userId;
const response = await store.payOrder(order, source);
```

You can then [attach it](https://stripe.com/docs/api/charges/create#create_charge-metadata) to the charge object created on the backend server:
https://github.com/stripe/stripe-payments-demo/blob/c242611d0abd2ca99ec0557d3cf5855657ade2cc/server/node/routes.js#L63-L75
```
charge = await stripe.charges.create(
          {
            source: source.id,
            amount: order.amount,
            metadata : {userId : order.userId}
            ....
         }
)
```

This issue tracker is for bugs or issues directly related to this project, and not for general support. Please feel free to reach out to https://support.stripe.com/email and we would be glad to help further!
